server:
  port: 8080 # Port for the API Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable dynamic routing based on Eureka discovery
        lower-case-service-id: true # Ensure service IDs are lowercase for routing
    loadbalancer:
      retry:
        enabled: true # Enable retries for failing instances
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
