server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8081 # Point directly to the user-service
          predicates:
            - Path=/api/users/**
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
